# Kakaopay Developers 에서 앱 생성 후 발급받은 admin key
# Admin key created by App of KakaoDevelopers
kakaopay.api.secret.key: DEV165ECEF683892DCAE7B159EE3DA02D090BC46

# Kakaopay 로부터 전달받은 가맹점 ID
# partner payment id from KakaoPay
cid: TC0ONETIME

front:
  host: http://localhost:3000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dna
    username: vtw
    password: vtw123#
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
